/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowAuthentification (void);
GtkWidget* create_windowListe (void);
GtkWidget* create_windowGRH (void);
GtkWidget* create_windowMeilleur (void);
GtkWidget* create_windowTaux (void);
GtkWidget* create_windowAjouter (void);
GtkWidget* create_windowModifier (void);
GtkWidget* create_windowSupprimer (void);
