/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *windowAuthentification;
  GtkWidget *windowListe;
  GtkWidget *windowGRH;
  GtkWidget *windowMeilleur;
  GtkWidget *windowTaux;
  GtkWidget *windowAjouter;

GtkWidget *treeview;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */


  windowListe = create_windowListe ();
  gtk_widget_show (windowListe);
  treeview=lookup_widget(windowListe,"treeviewListeOuvriers");
affichage_ouvrier(treeview);
   /* windowAuthentification = create_windowAuthentification ();
  gtk_widget_show (windowAuthentification);


affichage_ouvrier(treeview);*/

  /* windowGRH = create_windowGRH ();
  gtk_widget_show (windowGRH);
   windowMeilleur = create_windowMeilleur ();
  gtk_widget_show (windowMeilleur);
  windowTaux = create_windowTaux ();
  gtk_widget_show (windowTaux);
  
windowAjouter = create_windowAjouter ();
  gtk_widget_show (windowAjouter);
*/

  gtk_main ();
  return 0;
}

